# Generated by Django 2.1.1 on 2019-07-29 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0004_auto_20190729_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='goods_imag',
            field=models.ImageField(default='/static/buyer/images/goods/adv01.jpg', upload_to='', verbose_name='商品图片'),
            preserve_default=False,
        ),
    ]
