# Generated by Django 2.1.1 on 2019-07-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_auto_20190725_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_data',
            field=models.DateField(blank=True, null=True, verbose_name='出厂日期'),
        ),
    ]
