# Generated by Django 2.1.1 on 2019-07-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20190725_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodstype',
            name='picture',
            field=models.ImageField(upload_to='store/images', verbose_name='商品类型图片'),
        ),
    ]
