# Generated by Django 2.1.1 on 2019-07-26 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_auto_20190725_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Store.GoodsType', verbose_name='商品类型'),
            preserve_default=False,
        ),
    ]
