# Generated by Django 2.1.1 on 2019-07-29 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_auto_20190726_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='store_id',
        ),
        migrations.AddField(
            model_name='goods',
            name='store_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Store.Store', verbose_name='店铺id'),
            preserve_default=False,
        ),
    ]
